app1/urls.py
from django.urls import path 
from app1.views import *
app_name='app1'
urlpatterns=[
    path('gt/',gt,name='gt'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *
from app2.views import *
import app1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mi/',mi,name='mi'),
    path('app1/',include('app1.urls')),
    path('rr/',rr,name='rr'),
]

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def mi(request):
    return render(request,'mi.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def gt(request):
    return render(request,'gt.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def rr(request):
    return render(request,'rr.html')

templates/gt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="background-color:aqua;color:orange;">This is gt html page</h1>
    <h1 style="color:cadetblue;background-color:bisque">gt captain is Hardik pandia</h1>
    <a href="{% url 'mi' %}">go another mi page</a>
   <h1><a href="{% url 'rr' %}">go to next page</a></h1>
</body> 
</html>

templates/mi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color:brown">This is mi html page</h1>
    <h1 style='color:blueviolet'>mi captain is Rohit sharma</h1>
    <a href="{% url 'app1:gt' %}">go to gt page</a>
</body>
</html>

templates/rr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>rr is a ipl team</h1>
    <h1>The captain is sanju</h1>
    <h1><a href="{% url 'app1:gt' %}">go to gt page</a></h1>
   <h1><a href="{% url 'mi' %}">go another mi page</a></h1>
</body>
</html>